version: '3.8'

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy:latest
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
      - ./certs:/etc/nginx/certs:ro
      - ./nginx.conf:/etc/nginx/conf.d/custom.conf:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy

  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    restart: unless-stopped
    depends_on:
      - nginx-proxy
    volumes:
      - ./certs:/etc/nginx/certs
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /etc/nginx/vhost.d
      - /usr/share/nginx/html
    environment:
      - DEFAULT_EMAIL=admin@tudominio.com
    networks:
      - proxy

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: unless-stopped
    environment:
      - VIRTUAL_HOST=n8n.midominio.com
      - LETSENCRYPT_HOST=n8n.midominio.com
      - LETSENCRYPT_EMAIL=admin@tudominio.com
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - WEBHOOK_URL=https://n8n.midominio.com/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - proxy

volumes:
  n8n_data:
  certs:

networks:
  proxy:
    external: false
