apiVersion: v1
kind: Secret
metadata:
  name: n8n-secret1
  namespace: default
type: Opaque
stringData:
  encryptionKey: lJynsrJd1zvHOakzKLd7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: n8n-data1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: standard-retain
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
        - name: fix-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 1000:1000 /data"]
          volumeMounts:
            - name: n8n-data
              mountPath: /data
      containers:
        - name: n8n
          image: n8nio/n8n
          resources:
            requests:
              cpu: "250m"
              memory: "512Mi"
            limits:
              cpu: "500m"
              memory: "1Gi"
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 20
          ports:
            - containerPort: 5678
          env:
            - name: N8N_HOST
              value: "n8n.laboratoriosconcristian.site"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_PROTOCOL
              value: "https"
            - name: N8N_ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: n8n-secret1
                  key: encryptionKey
            - name: N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS
              value: "true"
            - name: N8N_RUNNERS_ENABLED
              value: "true"
          volumeMounts:
            - name: n8n-data
              mountPath: /home/node/.n8n
          securityContext:
            runAsUser: 1000
            runAsGroup: 1000
      volumes:
        - name: n8n-data
          persistentVolumeClaim:
            claimName: n8n-data1
---
apiVersion: v1
kind: Service
metadata:
  name: n8n
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: n8n
  ports:
    - name: http
      port: 5678
      targetPort: 5678
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: n8n-ingress
  namespace: default
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - n8n.laboratoriosconcristian.site
      secretName: n8n-tls
  rules:
    - host: n8n.laboratoriosconcristian.site
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: n8n
                port:
                  number: 5678
